# Timing

In [1]:
%timeit [j**4 for j in range(1,9)]                             #timing for compilation

4.48 µs ± 331 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [5]:
import numpy as np
%timeit np.arange(1,9)

1.28 µs ± 77 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
l= []
for i in range(1,5):
    int_l=int(input("Enter: "))
    l.append(int_l)                                            #range of the array
    print(np.array(l))


Enter: 4
[4]
Enter: 5
[4 5]
Enter: 6
[4 5 6]
Enter: 7
[4 5 6 7]


In [9]:
ar2 = np.array([[1,2,3,4],[4,5,6,7]])
ar2                                                   #2 dimensional array

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [12]:
ar2 = np.array([[1,2,3,4],[4,5,6,7]])            #2 dimensions array
print(ar2)
print(ar2.ndim)         #for finding the dimensions

[[1 2 3 4]
 [4 5 6 7]]
2


In [14]:
ar3=np.array([[[1,2,3,4,5],[3,4,6,7,8],[4,5,6,7,8]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4 5]
  [3 4 6 7 8]
  [4 5 6 7 8]]]
3


# Zeroes

In [20]:
import numpy as np
ar_zeros=np.zeros(4)             #zeroes to the all elements
ar_zeros1=np.zeros((3,4))

print(ar_zeros)
print()
print(ar_zeros1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [22]:
import numpy as np                     #converting all the array numbers in '1'
ar_ones=np.ones(8)
print(ar_ones)

[1. 1. 1. 1. 1. 1. 1. 1.]


# Empty

In [24]:
ar_em = np.empty(4)                        #empty array num'0'
print(ar_em)

[0. 0. 0. 0.]


# Range

In [26]:
ar_rn=np.arange(4)
print(ar_rn)                              #Ranges of array

[0 1 2 3]


# Digonal

In [27]:
ar_dia=np.eye(3)
print(ar_dia)                               #diagonal to the array

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
ar_dia=np.eye(4,5)
print(ar_dia)                              With limited range diagonal array

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


# Linespace

In [39]:
ar_lin=np.linspace(0,20,num=5)                  #linspace multiple for array
print(ar_lin)

[ 0.  5. 10. 15. 20.]
